### PR TITLE
Update assignments.md

### PR DESCRIPTION
**Pull request by JisooSeo**

### CODE REVIEW

**Review by giacomodecolle — CHANGES_REQUESTED** [review]
Line 573, A ref and B asymm doesn't create any contradiction according to our table and my Protege

**Comment by giacomodecolle** [comment]
Line 578, A/Bi doesn't create contradictions according to our table and my protege

**Comment by giacomodecolle** [comment]
Line 584, Ai/B doesn't create any contradictions according to our table and my protege

**Comment by giacomodecolle** [comment]
Line 587, Ai/Bi doesn't create any contradictions according to our table and my protege

**Comment by giacomodecolle** [comment]
For Ref/Asymm are also missing

- B/Ai

- Bi/A

- Bi/Ai

- B/A

**Comment by JisooSeo** [comment]
For Ref/Asymm, B/Ai, Bi/A, Bi/Ai, B/A don't have errors.

**Comment by giacomodecolle** [comment]
Ok, just to make sure we are talking about the same thing: I mean B ref, Ai asymm. Bi ref, A asymm. Bi ref, Ai asymm. B ref, A symm. They all produce errors according to this table
 
image

**Comment by JisooSeo** [comment]
So " B ref, Ai asymm. Bi ref, A asymm. Bi ref, Ai asymm. B ref, A symm" are just "Ai asymm/B ref, A asymm/Bi ref, Ay asymm/Bi ref, A asymm/B ref" and I covered them. I only need to do explanations for 8 things and that's what I have.

**Pull request merged**
